version: '3.4'

services:
  ecommerce.api.customers:
    image: ${DOCKER_REGISTRY-}ecommerceapicustomers
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: ECommerce.Api.Customers/Dockerfile
    ports:
      - '6003:80'

  ecommerce.api.orders:
    image: ${DOCKER_REGISTRY-}ecommerceapiorders
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: ECommerce.Api.Orders/Dockerfile
    ports:
      - '6002:80'

  ecommerce.api.products:
    image: ${DOCKER_REGISTRY-}ecommerceapiproducts
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: ECommerce.Api.Products/Dockerfile
    ports:
      - '6001:80'

  ecommerce.api.search:
    image: ${DOCKER_REGISTRY-}ecommerceapisearch
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Products=http://ecommerce.api.products
      - Services__Customers=http://ecommerce.api.customers
      - Services__Orders=http://ecommerce.api.orders
    build:
      context: .
      dockerfile: ECommerce.Api.Search/Dockerfile
    ports:
      - '6004:80'
