version: '3.4'

services:
  customers:
    image: brenomar/ecommerceapicustomers:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"

  orders:
    image: brenomar/ecommerceapiorders:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"
    
  products:
    image: brenomar/ecommerceapiproducts:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"

  search:
    image: brenomar/ecommerceapisearch:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Products=http://products.lil
      - Services__Customers=http://customers.lil
      - Services__Orders=http://orders.lil
    ports:
      - "6004:80"

